### ISSUE TITLE
Loading Saved Networks

### ISSUE THREAD

**Issue by zippynl** [mbithy/Trevel#12]
Great stuff with the wiki! but 1 thing is not clear.

What do you mean with this:
**Make sure that your var spec = {} match what you trained with**
Do you have a example what it could be?

And this. When i copy the DQ-Trevel.js in the console
and i do the 
**var netString='copy paste your network model here';
var netObject=JSON.parse(netString);
agent.fromJSON(netObject);**
with the trained network code paste {"W1":{"n":10,"d":24,"w":{"0":0.00239 etc 626654111294}}}
it gives the error
**Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at <anonymous>:2:20**

What am i doing wrong?

**Comment by osavigne** [comment]
check if there is any space in the first position when you copy the trained network on the `´´`

**Comment by mbithy** [comment]
see what @osavigne and make sure you don't include double quotes " in between the ' single quotes
var spec is the variable spec in DQ-Trevel its  noted in the comments
```js
//if you are loading a trainned network the values here should match your trainning values
spec.epsilon = 0.20;
spec.alpha = 0.1;
spec.experience_add_every = 5;
spec.experience_size = 999999;
spec.learning_steps_per_iteration = 5;
spec.tderror_clamp = 1.0; 
spec.num_hidden_units = 100;
```

**Comment by zippynl** [comment]
So i did it like this(i took code from the middle so its not that long:
var netString='{"nh":100,"ns":5,"na":2,"net":{"W1":{"n":100,"d":5,"w":{"0":-0.19900864127143897,"1":-0.061143301242088915,"2":-0.5012762985210412,"3":-0.05593718023682009,"4":0.009160040719231417,"5":,"199":0.19622962316565892}},"b2":{"n":2,"d":1,"w":{"0":0.10431418654902055,"1":0.13216833544777085}}}}';
var netObject=JSON.parse(netString);
agent.fromJSON(netObject);

And then it gave a "undefined". Did i do it correct?

**Comment by osavigne** [comment]
@zippynl did you have skype or something else to get in touch to explain you better how do that?

**Comment by zippynl** [comment]
@osavigne yes i have skype, add me zippy_nl
