### ISSUE TITLE
improve after learning?

### ISSUE THREAD

**Issue by panda2048** [mbithy/Trevel#14]
I am expecting the DQN was there to improve the "dice guess", so over time, the max loose streak will be lower down (i.e. lower down the min. satoish required to start)
But after running for 2 millions round. I do not actually seeing significant change
Is my understanding correct?
If so, when should we expect the improvement?

**Comment by mbithy** [comment]
yup, theoretically, this could be an indication that there is no advantage to be gained by using MA OR the ReinforceJS mathematical equations aren't capable of beating the randomness of provably fair OR we(me) from start are using the wrong "inputs" to try and get a MA algorithm to find a pattern... I'm leaning on the first one.

**Comment by osavigne** [comment]
i add a implementation of SVM (Support Vector Machine) to this DRL (Deep Reinforcement Learning) algorithm and try the simulator and now after 20 million of bets is starting to decrease currently 8 loose streak top the last 50 bets, i want to give a try before publish any of this, but my account balance is to low, now on 0.00010334 btc, i am waiting to increase a few more satochis to test it

**Comment by mbithy** [comment]
@osavigne cool stuff, I would like to see

**Comment by osavigne** [comment]
we wil have to wait @mbithy , but if you want to help just transfer me some satochis to my freebitco.in account to start testing with more balance because i have right now only 0.00012036 btc
