### ISSUE TITLE
Ghost bets

### ISSUE THREAD

**Issue by kazi308** [mbithy/Trevel#15]
Hi, I was wondering if anyone has any ideas of how to prevent ghost bets?

Thanks

**Comment by mbithy** [comment]
don't be faster than your internet also the website may delay the response time just to make sure you are not a bot when they notice many requests

**Comment by kazi308** [comment]
I am wondering if there is  any way to confirm the response before continuing the loop...

**Comment by xcape** [comment]
Hi, i am trying this to prevent "max time out"
```

// to stop in timeout
 $(document).ajaxStop(function () {
	var timeout= $("#double_your_btc_error").html();
	if (timeout!=""){
		console.log("Stop to bet, to preevent leaks");
		env.stop=true;
	}
  });
```

**Comment by abadieferu** [comment]
@xcape Please Can you advise on which part of the code I can place the suggested function?

```$(document).ajaxStop(function () {
	var timeout= $("#double_your_btc_error").html();
	if (timeout!=""){
		console.log("Stop to bet, to preevent leaks");
		env.stop=true;
	}
  });```
