### ISSUE TITLE
problem with trevelDQ

### ISSUE THREAD

**Issue by Parzival33** [mbithy/Trevel#16]
Please can anybody help me?
Im not sure if done everything right, i took trevelDQ, i put the trained network into var netString just like this:

var netString={"W1":{"n" :10, "d":24, "w":{"0":0.0023925765403397733,"1":0.041715507090969335,"2":0.021888390238649903,"3":-0.0009391853385634892,"4":0.022507000788136614,"5":0.010639511213428482,"6":0.0012826647767140032,"7":-0.0029160858320425743,"8":-0.01796780336575986,"9":0.022672443128039375,"10":-0.007832676396745026,"11":-0.01850579461846927,"12":-0.011700259716593303,"13":0.000628374696150096,"14":-0.019122314781445476,"15":-0.0583388663305787,"16":0.013655957276794974,"17":-0.017566968641159742,"18":0.009833933367455942,"19":-0.03518118297776568,"20":0.0408489419214892,"21":-0.02608618686810133,"22":-0.003429737655522844,"23":0.009770451021620328,"24":0.01410770805100909,"25":-0.03139741654541435,"26":0.031111624422918555,"27":-0.003848954648549595,"28":0.012183498553807176,"29":-0.01998645708420641,"30":-0.006724626595390829,"31":0.005310766950190668,"32":-0.015524644342140568,"33":-0.028928401987948833,"34":-0.012944071457811089,"35":-0.06218620424803521,"36":-0.027049031282310804,"37":-0.0012133947238548136,"38":0.006354270610894588,"39":-0.022600484619600125,"40":-0.018427681654901756,"41":-0.027582646784811735,"42":-0.04377075439499172,"43":0.010344167930596974,"44":-0.010457416918694448,"45":-0.008091993016985051,"46":0.008672319645495136,"47":0.04325112784304685,"48":-0.04096514836443519,"49":-0.04395467694947917,"50":0.02547501778341822,"51":0.039554361294374035,"52":0.007275896314646853,"53":0.004739097302510623,"54":0.03991856765640677,"55":0.007184925392409339,"56":0.017625001761796242,"57":0.024920351290448558,"58":-0.00615826079973909,"59":0.0016350522524687361,"60":0.016161138130802204,"61":0.025517456704768487,"62":-0.02545507131952735,"63":0.0036360618598252725,"64":0.018206834213719103,"65":-0.025682072627037287,"66":0.0100312248321219,"67":-0.023015477424917545,"68":-0.01303847978661533,"69":-0.013694029083706056,"70":0.016366028546751888,"71":-0.003318077396385832,"72":-0.011193010811942076,"73":-0.026267686887636053,"74":-0.04251753916780317,"75":-0.07058127775249927,"76":-0.0657147601212925,"77":-0.013854085504026645,"78":-0.031594790048150447,"79":-0.01732804261211277,"80":-0.028430129428590745,"81":0.027214854498239745,"82":0.01868249963946485,"83":0.020209397054480254,"84":-0.01658568606288791,"85":0.026344319795758468,"86":0.011190203088180174,"87":-0.03546670632380143,"88":0.005305463719931446,"89":0.005257910492120129,"90":0.004771761851734521,"91":0.031365967065046706,"92":0.003047637825499757,"93":0.017659404304856477,"94":0.027382416581660254,"95":0.020925895416983364,"96":-0.01687460274789406,"97":0.021454458463242492,"98":-0.0012471938319427688,"99":0.01034782942132612,"100":0.02685066054405012,"101":0.021656960615436708,"102":-0.012849907470087192,"103":0.01805413045232617,"104":-0.004931566966478788,"105":0.006520311541459502,"106":0.02435813645686764,"107":0.006817645572144121,"108":-0.021338393684633236,"109":0.00286944810014431,"110":0.03375230802914669,"111":-0.026825375073172238,"112":-0.02115980297742884,"113":-0.03103988196770537,"114":-0.04300222382401059,"115":0.02130765757070038,"116":-0.021180164325246692,"117":-0.03618614897872891,"118":-0.01891251451073892,"119":0.01050026202118535,"120":-0.008075871768834876,"121":-0.034811425222634036,"122":0.0016995591783181203,"123":-0.017650344881800673,"124":0.009642095967872945,"125":-0.000025504562980153146,"126":0.0018029203285039503,"127":0.013234384740577027,"128":-0.0372770952098072,"129":0.0030208793642159193,"130":-0.0012243593402471488,"131":-0.002341006340765817,"132":0.03655162534569215,"133":-0.008170548319799709,"134":0.0038241934200167137,"135":-0.01165933137711159,"136":-0.0017615274539351253,"137":-0.011792070004941261,"138":0.006266635502956271,"139":-0.033307121876295726,"140":-0.007351541627479688,"141":-0.01876229682924831,"142":-0.04237737876138415,"143":-0.03026875860138129,"144":0.021597084637609197,"145":-0.012577309249815594,"146":0.029249658261437397,"147":0.012170767931970378,"148":-0.023651885974338527,"149":0.020686435854327365,"150":-0.015174762380851976,"151":-0.00384707419412265,"152":0.0280638257777172,"153":0.006728850995434008,"154":0.020639473770229434,"155":-0.013738706948945157,"156":-0.053173000680836975,"157":-0.0025286773398094146,"158":-0.00954051653222256,"159":-0.021273767469663755,"160":-0.030675301158921083,"161":0.030209521942635126,"162":0.04163028531549313,"163":-0.0006381561611404614,"164":-0.0046019400638133675,"165":-0.007972341151336267,"166":-0.027135798395529053,"167":-0.024803364927611225,"168":-0.017268863362656886,"169":-0.006220284895158575,"170":-0.03511726179296469,"171":0.006436356163974951,"172":0.014065149789953069,"173":-0.046767146091149084,"174":-0.034930196429677235,"175":0.02937646322813344,"176":0.008531325622594354,"177":-0.012231105432745274,"178":0.015076274760503152,"179":0.00448625847625719,"180":-0.030506011250670737,"181":-0.02086840531962036,"182":-0.011868518852966031,"183":0.022171999622510225,"184":-0.029025840985756383,"185":-0.031152338367179386,"186":0.016296667894623123,"187":-0.015183866723327421,"188":-0.0059567109536374984,"189":-0.013605608384929661,"190":0.01630487488752131,"191":-0.024125280474780467,"192":-0.0073355377436716,"193":-0.031283796784592095,"194":-0.009303105940331246,"195":-0.019892137554844196,"196":0.03999268199400648,"197":0.009444224219226863,"198":0.002671918881159383,"199":0.032491706199356415,"200":0.024246372641324544,"201":-0.0005700355062285601,"202":0.02060188635993488,"203":0.016939323027312613,"204":-0.03499699840542014,"205":-0.05105351027010581,"206":-0.04195850593559798,"207":-0.03127298650747034,"208":-0.007588428193512317,"209":-0.0046029585802638455,"210":-0.022527756042589813,"211":-0.02217593917928543,"212":-0.002069831320825874,"213":0.034996877127942985,"214":0.017451886562628558,"215":0.009899297719319702,"216":-0.01942692004883715,"217":-0.0022115758635712353,"218":-0.010155874037456379,"219":-0.004884936693766227,"220":-0.026184486835125673,"221":-0.011759223403801028,"222":0.044656471116086664,"223":0.02336848486843356,"224":-0.020458733185087372,"225":-0.019597785549344462,"226":0.009052927384547375,"227":0.010051056776690827,"228":-0.012245028259093658,"229":0.025053267013094006,"230":0.054694559709263194,"231":0.0079385659551661,"232":0.002635064840418802,"233":0.013390248804876423,"234":-0.013670952805131023,"235":-0.054888963906016365,"236":-0.003967167132215167,"237":-0.013659943922532745,"238":0.01423808219615499,"239":0.008316574721174103}},"b1":{"n":10,"d":1,"w":{"0":-0.0020860370242000753,"1":-0.003593492292501457,"2":0.005181375364556662,"3":0.03859672545627185,"4":-0.00811978133752935,"5":0.022901925677714076,"6":0.024167562133460073,"7":0.02692800396722249,"8":0.037381107638321656,"9":0.021098709799853937}},"W2":{"n":2,"d":10,"w":{"0":0.03381494044095179,"1":0.020461054386859998,"2":-0.01964189874707836,"3":-0.03539441083769555,"4":0.006255717754153956,"5":-0.009766022749077325,"6":0.03639734454989264,"7":-0.01598061411063054,"8":0.0052980443461223565,"9":-0.00312026563476357,"10":0.017820905721491885,"11":-0.027050763584985038,"12":0.02938041662246762,"13":-0.03975678417885278,"14":-0.03401224310882197,"15":-0.01139647805524638,"16":0.013951290794576104,"17":-0.015420045929063042,"18":-0.0022168643262469026,"19":-0.03193927829973052}},"b2":{"n":2,"d":1,"w":{"0":-0.13247979962126746,"1":-0.1409626654111294}}}

when i execute this console log says undefined, then I execute this:

var netObject=JSON.parse(netString);

and it says undefined again, then i execute this:

agent.fromJSON(netObject);

and then it says that m1 is not defined.

could someone help me? i dont know if i understood correctly the solution must be simple
thank you!

**Comment by Parzival33** [comment]
Please can anybody help me?
Im not sure if done everything right, i took trevelDQ, i put the trained network into var netString just like this:

var netString=`{"W1":{"n" :10, "d":24, "w":{"0":0.0023925765403397733,"1":0.041715507090969335,"2":0.021888390238649903,"3":-0.0009391853385634892,"4":0.022507000788136614,"5":0.010639511213428482,"6":0.0012826647767140032,"7":-0.0029160858320425743,"8":-0.01796780336575986,"9":0.022672443128039375,"10":-0.007832676396745026,"11":-0.01850579461846927,"12":-0.011700259716593303,"13":0.000628374696150096,"14":-0.019122314781445476,"15":-0.0583388663305787,"16":0.013655957276794974,"17":-0.017566968641159742,"18":0.009833933367455942,"19":-0.03518118297776568,"20":0.0408489419214892,"21":-0.02608618686810133,"22":-0.003429737655522844,"23":0.009770451021620328,"24":0.01410770805100909,"25":-0.03139741654541435,"26":0.031111624422918555,"27":-0.003848954648549595,"28":0.012183498553807176,"29":-0.01998645708420641,"30":-0.006724626595390829,"31":0.005310766950190668,"32":-0.015524644342140568,"33":-0.028928401987948833,"34":-0.012944071457811089,"35":-0.06218620424803521,"36":-0.027049031282310804,"37":-0.0012133947238548136,"38":0.006354270610894588,"39":-0.022600484619600125,"40":-0.018427681654901756,"41":-0.027582646784811735,"42":-0.04377075439499172,"43":0.010344167930596974,"44":-0.010457416918694448,"45":-0.008091993016985051,"46":0.008672319645495136,"47":0.04325112784304685,"48":-0.04096514836443519,"49":-0.04395467694947917,"50":0.02547501778341822,"51":0.039554361294374035,"52":0.007275896314646853,"53":0.004739097302510623,"54":0.03991856765640677,"55":0.007184925392409339,"56":0.017625001761796242,"57":0.024920351290448558,"58":-0.00615826079973909,"59":0.0016350522524687361,"60":0.016161138130802204,"61":0.025517456704768487,"62":-0.02545507131952735,"63":0.0036360618598252725,"64":0.018206834213719103,"65":-0.025682072627037287,"66":0.0100312248321219,"67":-0.023015477424917545,"68":-0.01303847978661533,"69":-0.013694029083706056,"70":0.016366028546751888,"71":-0.003318077396385832,"72":-0.011193010811942076,"73":-0.026267686887636053,"74":-0.04251753916780317,"75":-0.07058127775249927,"76":-0.0657147601212925,"77":-0.013854085504026645,"78":-0.031594790048150447,"79":-0.01732804261211277,"80":-0.028430129428590745,"81":0.027214854498239745,"82":0.01868249963946485,"83":0.020209397054480254,"84":-0.01658568606288791,"85":0.026344319795758468,"86":0.011190203088180174,"87":-0.03546670632380143,"88":0.005305463719931446,"89":0.005257910492120129,"90":0.004771761851734521,"91":0.031365967065046706,"92":0.003047637825499757,"93":0.017659404304856477,"94":0.027382416581660254,"95":0.020925895416983364,"96":-0.01687460274789406,"97":0.021454458463242492,"98":-0.0012471938319427688,"99":0.01034782942132612,"100":0.02685066054405012,"101":0.021656960615436708,"102":-0.012849907470087192,"103":0.01805413045232617,"104":-0.004931566966478788,"105":0.006520311541459502,"106":0.02435813645686764,"107":0.006817645572144121,"108":-0.021338393684633236,"109":0.00286944810014431,"110":0.03375230802914669,"111":-0.026825375073172238,"112":-0.02115980297742884,"113":-0.03103988196770537,"114":-0.04300222382401059,"115":0.02130765757070038,"116":-0.021180164325246692,"117":-0.03618614897872891,"118":-0.01891251451073892,"119":0.01050026202118535,"120":-0.008075871768834876,"121":-0.034811425222634036,"122":0.0016995591783181203,"123":-0.017650344881800673,"124":0.009642095967872945,"125":-0.000025504562980153146,"126":0.0018029203285039503,"127":0.013234384740577027,"128":-0.0372770952098072,"129":0.0030208793642159193,"130":-0.0012243593402471488,"131":-0.002341006340765817,"132":0.03655162534569215,"133":-0.008170548319799709,"134":0.0038241934200167137,"135":-0.01165933137711159,"136":-0.0017615274539351253,"137":-0.011792070004941261,"138":0.006266635502956271,"139":-0.033307121876295726,"140":-0.007351541627479688,"141":-0.01876229682924831,"142":-0.04237737876138415,"143":-0.03026875860138129,"144":0.021597084637609197,"145":-0.012577309249815594,"146":0.029249658261437397,"147":0.012170767931970378,"148":-0.023651885974338527,"149":0.020686435854327365,"150":-0.015174762380851976,"151":-0.00384707419412265,"152":0.0280638257777172,"153":0.006728850995434008,"154":0.020639473770229434,"155":-0.013738706948945157,"156":-0.053173000680836975,"157":-0.0025286773398094146,"158":-0.00954051653222256,"159":-0.021273767469663755,"160":-0.030675301158921083,"161":0.030209521942635126,"162":0.04163028531549313,"163":-0.0006381561611404614,"164":-0.0046019400638133675,"165":-0.007972341151336267,"166":-0.027135798395529053,"167":-0.024803364927611225,"168":-0.017268863362656886,"169":-0.006220284895158575,"170":-0.03511726179296469,"171":0.006436356163974951,"172":0.014065149789953069,"173":-0.046767146091149084,"174":-0.034930196429677235,"175":0.02937646322813344,"176":0.008531325622594354,"177":-0.012231105432745274,"178":0.015076274760503152,"179":0.00448625847625719,"180":-0.030506011250670737,"181":-0.02086840531962036,"182":-0.011868518852966031,"183":0.022171999622510225,"184":-0.029025840985756383,"185":-0.031152338367179386,"186":0.016296667894623123,"187":-0.015183866723327421,"188":-0.0059567109536374984,"189":-0.013605608384929661,"190":0.01630487488752131,"191":-0.024125280474780467,"192":-0.0073355377436716,"193":-0.031283796784592095,"194":-0.009303105940331246,"195":-0.019892137554844196,"196":0.03999268199400648,"197":0.009444224219226863,"198":0.002671918881159383,"199":0.032491706199356415,"200":0.024246372641324544,"201":-0.0005700355062285601,"202":0.02060188635993488,"203":0.016939323027312613,"204":-0.03499699840542014,"205":-0.05105351027010581,"206":-0.04195850593559798,"207":-0.03127298650747034,"208":-0.007588428193512317,"209":-0.0046029585802638455,"210":-0.022527756042589813,"211":-0.02217593917928543,"212":-0.002069831320825874,"213":0.034996877127942985,"214":0.017451886562628558,"215":0.009899297719319702,"216":-0.01942692004883715,"217":-0.0022115758635712353,"218":-0.010155874037456379,"219":-0.004884936693766227,"220":-0.026184486835125673,"221":-0.011759223403801028,"222":0.044656471116086664,"223":0.02336848486843356,"224":-0.020458733185087372,"225":-0.019597785549344462,"226":0.009052927384547375,"227":0.010051056776690827,"228":-0.012245028259093658,"229":0.025053267013094006,"230":0.054694559709263194,"231":0.0079385659551661,"232":0.002635064840418802,"233":0.013390248804876423,"234":-0.013670952805131023,"235":-0.054888963906016365,"236":-0.003967167132215167,"237":-0.013659943922532745,"238":0.01423808219615499,"239":0.008316574721174103}},"b1":{"n":10,"d":1,"w":{"0":-0.0020860370242000753,"1":-0.003593492292501457,"2":0.005181375364556662,"3":0.03859672545627185,"4":-0.00811978133752935,"5":0.022901925677714076,"6":0.024167562133460073,"7":0.02692800396722249,"8":0.037381107638321656,"9":0.021098709799853937}},"W2":{"n":2,"d":10,"w":{"0":0.03381494044095179,"1":0.020461054386859998,"2":-0.01964189874707836,"3":-0.03539441083769555,"4":0.006255717754153956,"5":-0.009766022749077325,"6":0.03639734454989264,"7":-0.01598061411063054,"8":0.0052980443461223565,"9":-0.00312026563476357,"10":0.017820905721491885,"11":-0.027050763584985038,"12":0.02938041662246762,"13":-0.03975678417885278,"14":-0.03401224310882197,"15":-0.01139647805524638,"16":0.013951290794576104,"17":-0.015420045929063042,"18":-0.0022168643262469026,"19":-0.03193927829973052}},"b2":{"n":2,"d":1,"w":{"0":-0.13247979962126746,"1":-0.1409626654111294}}}`

when i execute this console log says undefined, then I execute this:

var netObject=JSON.parse(netString);

and it says undefined again, then i execute this:

agent.fromJSON(netObject);

and then it says that m1 is not defined.

could someone help me? 
thank you!

**Comment by mbithy** [comment]
You should be using DQ-Trevel.js also read the WIKI. Your net should be within single quotes
