### ISSUE TITLE
Change the initial bet

### ISSUE THREAD

**Issue by MistAgeNetKasper** [mbithy/Trevel#2]
Hi, tell me how can I change the initial bet
Current initial bet: 0.00000001
Example bet: 0.00000002 or 0.00000010
And when will update?

**Comment by mbithy** [comment]
Well @MistAgeNetKasper You are in Luck, I just pushed new changes use changeset [32231dacec](https://github.com/mbithy/Trevel/blob/32231dacec5de4f300936c86c576af44cfcf694a/Trevel.js)
Instruction are provided as comments in the code. Have Fun with it!!

**Comment by MistAgeNetKasper** [comment]
why 
https://0sc.ru/LlaC1OBL1x
