### ISSUE TITLE
Bad work

### ISSUE THREAD

**Issue by MistAgeNetKasper** [mbithy/Trevel#3]
why?

![Wrong Log](https://0sc.ru/LlaC1OBL1x)
My balance was: 0.00008300 BTC
Then he rose up: 0.00010900 BTC
And that goes to: 0.0002500 BTC
My settings:
var _stop = false,
    _rolls = 0,
    _currentBalance, _maxBet, _x = 0,
    _maxNumberOfTrails=10000,
    _minNumberOfTrials=5000,
    _numberOfSuccesses = 0,
    _numberOfTrials = 0,
    _winPercentage = 52,
    _stopOnNumberOfBets = false, //Change this to true if you wish to stop betting after a specific number of bets
    _defaultProb=false,
    _swap = true,
    _verbose = false, //Change this to true if you want to know the stats(profit) after each bet
    _numberOfBets = 46, //You can change this but keep the number of bets low (<135 but >75) to increse AI accuracy.
    _maxNumberOfBets = 50, //max=150
    _minNumberOfBets = 50, // min=50
    /** Custom Bet Configuration **/
    _useCustomConfiguration=true,//Change to true to use your own configuration
    _customMaximumBet=0.00004096,//This is the maximum bet you want placed
    _customMinimumBet=0.00000002,//This is the minimum bet you want placed
    _customMultiplier=2;// This is the multiplier. the default is 2. INFO: The bet amount will be multiplied

**Comment by mbithy** [comment]
@MistAgeNetKasper Thanks for sporting that... A reset method was being called earlier than expected hence the weird values. I have fixed it though in chageset [d371fe3c9be2a](https://github.com/mbithy/Trevel/blob/d371fe3c9be2ac3be2d57a3a78607beea8507f21/Trevel.js) see ![this](http://trevel.quickbuckit.com/fixed.png)

**Comment by MistAgeNetKasper** [comment]
Thank you. 
When I gather at least 0.00007500 BTC TRAVEL I run and I will write you the result of his work
