### ISSUE TITLE
Add new betting strategies

### ISSUE THREAD

**Issue by MistAgeNetKasper** [mbithy/Trevel#4]
Maybe add [Martingale](https://en.wikipedia.org/wiki/Martingale_(betting_system))  betting strategies.
[Pull request for tampermoneky/greasmonkey](https://github.com/mbithy/Trevel/pull/5)

**Comment by mbithy** [comment]
[Added one more see this release](https://github.com/mbithy/Trevel/releases/tag/1.1.5.0)

**Comment by mbithy** [comment]
Also Martingale is already there. It is the default betting strategy...
