### ISSUE TITLE
Bet amount spiking unexpectedly

### ISSUE THREAD

**Issue by FloweryScythe13** [mbithy/Trevel#6]
On several occasions, I have noticed the bet amount being used by Trevel jumps up from the amount that I have it set to, usually causing unexpected losses of bitcoin. It happened again just now. I notice that these big amounts are usually a couple percent of my total balance - is this behavior related to the value of _amountToKelly, or is it an actual bug? It appears to ignore the value that I have set for _customMaximumBet.

Example log information from a run of several hundred bets where this behavior happened twice, where I stopped betting immediately after the second time (below): 

> 0.00033606
> VM70519:387 Profit: -0.00190299
> VM70519:397 Using computed probabilities above.
> VM70519:331 0.00015716
> VM70519:387 Profit: -0.00223905
> VM70519:397 Using computed probabilities above.
> VM70519:331 0.00000000
> VM70519:387 Profit: -0.00239621
> VM70519:397 Using computed probabilities above.
> _stop = true;
> true
> VM70519:331 -0.00014103
> VM70519:387 Profit: -0.00208189
> VM70519:397 Using computed probabilities above.
> VM70519:351 Betting Stopped. Your profit is: -0.00208189
> VM70519:352 In this round You have won 10 bets and lost 10 bets. Total bets placed are: 20
> VM70519:353 In total You have won 250 bets and lost 277 bets. Total bets placed are: 527
> VM70519:354 You have a 0.47 probability of winning with Trevel.

Here it jumped from a bet amount of 1 satoshi to 33,606 satoshi, then 15,716 satoshi, then 31,432 satoshi, then back down to 1 satoshi. 

My settings are:
```
var _stop = false,
    _rolls = 0,
    _currentBalance, _maxBet=0, _x = 0,
    _maxNumberOfTrails=10000,
    _minNumberOfTrials=5000,
    _numberOfSuccesses = 0,
    _numberOfTrials = 0,
    _winPercentage = 52,
    _stopOnNumberOfBets = false, //Change this to true if you wish to stop betting after a specific number of bets
    _defaultProb=false,
    _swap = true,
    _betSpeed = 4000,  
    /** INFO ON _betSpeed
    * If you want bets to go faster decrease the value 3000, recomended minimum is 1500 (at 1500 you'll need really fast internet and hope the freebitco.in server responds as fast)
    * If you want to go slower increase the value 3000, recomended max is 5000 (only option if you have tortoise internet)
    **/
    _verbose = true, //Change this to true if you want to know the stats(profit) after each bet
    _numberOfBets = 110, //You can change this but keep the number of bets low (<135 but >75) to increse AI accuracy.
    _maxNumberOfBets = 50, //max=150
    _minNumberOfBets = 50, // min=50
    /** Custom Bet Configuration **/
    _useCustomConfiguration=true,//Change to true to use your own configuration
    _amountToKelly=5, // Change this to set percentage of your full amount to be used in the Kelly Principle (Can not be more than 100)
    _useKellyPrinciple=true,//change to false to use martingale
    _customMaximumBet=0.00000500,//This is the maximum bet you want placed
    _customMinimumBet=0.00000001,//This is the minimum bet you want placed
    _customMultiplier=1.7;// This is the multiplier. the default is 2. INFO: The bet amount will be multiplied by this number incese you loose a bet
```

**Comment by mbithy** [comment]
You had set the speed to high or the website failed or was slow to respond i.e when sometimes the roll spins form more than it should and **the website returns a loss** when in reality there was _no outcome._ The bot continues and counts it as a loss thus incrementing the amount if martingale was enabled.

**Comment by mbithy** [comment]
Even when you are using Kelly principle, if many **false** losses are returned as mentioned above say on HI bet the probability of winning will drift to LO in this case and the bet fraction will increase dramatically causing the "spike" and if the bet placed with the increased fraction is a loss you would also see a spike in losses. The opposite is also true. If the spiked bet was a win you would see a spike in amount won. When this happens it would be best to set the speed to 5000 or check your internet response time a ping will get you those milliseconds.

**Comment by mbithy** [comment]
another not so obvious effect of using Kelly  is that the max bet will not at any point be more than what you have set, eg. if you have 400 satoshi and you Kelly  20% the bot will not wager more than 80 satoshi, it'll go back to 1 then recalculate again...

**Comment by kazi308** [comment]
Hi FloweryScythe13, this has to do with _amountToKelly as you have _useKellyPrinciple set to true.
