### ISSUE TITLE
Deep q learning using the reinforcejs library

### ISSUE THREAD

**Issue by kazi308** [mbithy/Trevel#7]
Hi mbithy,

I have made some changes to Trevel in my fork. I have implemented deep q learning using the reinforcejs library. I would love it if you could review the changes, point out any mistakes (I am very new to coding) and let me know how we could improve it.

https://github.com/kazi308/Trevel/blob/master/Trevel.js

Thanks

**Comment by mbithy** [comment]
@kazi308 cool stuff I will check it out. This is interesting machine learning in provably fair, I wonder how it will fair!!

**Comment by kazi308** [comment]
Hi @mbithy just wondering what your thoughts are in relation to this?

**Comment by mbithy** [comment]
@kazi308 Already done, see the DQ-Trevel.js in the latest commit

**Comment by kazi308** [comment]
Ah Great work! I look forward to testing it out. Is it possible to exchange emails?

**Comment by mbithy** [comment]
do you have telegram? @mbithy

**Comment by kazi308** [comment]
I don't but I will set one one up. What are your telegram details?

**Comment by mbithy** [comment]
use @mbithy is my username and Mbithi K my name
